DROP TABLE IF EXISTS Course CASCADE;
DROP TABLE IF EXISTS Auditorium CASCADE;
DROP TABLE IF EXISTS Study_Class CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS Teacher CASCADE;
DROP TABLE IF EXISTS CourseTeacher_Info CASCADE;
DROP TABLE IF EXISTS CourseStudent_Info CASCADE;
